# Generated by Django 2.2.7 on 2020-01-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(max_length=13)),
                ('year', models.CharField(max_length=10)),
                ('non_veg', models.NullBooleanField()),
            ],
        ),
    ]
